/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AgentesRouteImport } from './routes/agentes'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as FindingsRouteImport } from './routes/findings'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as UsoRouteImport } from './routes/uso'
import { Route as VerificarRouteImport } from './routes/verificar'
import { Route as ApiAgentRouteImport } from './routes/api.agent'
import { Route as EvidenceIndexRouteImport } from './routes/evidence.index'
import { Route as EvidenceEvidenceIdRouteImport } from './routes/evidence.$evidenceId'
import { Route as FindingsIndexRouteImport } from './routes/findings.index'
import { Route as FindingsFindingIdRouteImport } from './routes/findings.$findingId'
import { Route as GoalsIndexRouteImport } from './routes/goals.index'
import { Route as GoalsGoalIdRouteImport } from './routes/goals.$goalId'
import { Route as ApiAgentForgeRouteImport } from './routes/api.agent.forge'
import { Route as ApiAgentKeyRouteImport } from './routes/api.agent.key'
import { Route as ApiAgentOpenapiRouteImport } from './routes/api.agent.openapi'
import { Route as ApiAgentPresenceRouteImport } from './routes/api.agent.presence'
import { Route as ApiAgentSkillRouteImport } from './routes/api.agent.skill'
import { Route as ApiAgentVerifyRouteImport } from './routes/api.agent.verify'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentesRoute = AgentesRouteImport.update({
  id: '/agentes',
  path: '/agentes',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const FindingsRoute = FindingsRouteImport.update({
  id: '/findings',
  path: '/findings',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const UsoRoute = UsoRouteImport.update({
  id: '/uso',
  path: '/uso',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificarRoute = VerificarRouteImport.update({
  id: '/verificar',
  path: '/verificar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentRoute = ApiAgentRouteImport.update({
  id: '/api/agent',
  path: '/api/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceIndexRoute = EvidenceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EvidenceRoute,
} as any)
const EvidenceEvidenceIdRoute = EvidenceEvidenceIdRouteImport.update({
  id: '/$evidenceId',
  path: '/$evidenceId',
  getParentRoute: () => EvidenceRoute,
} as any)
const FindingsIndexRoute = FindingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FindingsRoute,
} as any)
const FindingsFindingIdRoute = FindingsFindingIdRouteImport.update({
  id: '/$findingId',
  path: '/$findingId',
  getParentRoute: () => FindingsRoute,
} as any)
const GoalsIndexRoute = GoalsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GoalsRoute,
} as any)
const GoalsGoalIdRoute = GoalsGoalIdRouteImport.update({
  id: '/$goalId',
  path: '/$goalId',
  getParentRoute: () => GoalsRoute,
} as any)
const ApiAgentForgeRoute = ApiAgentForgeRouteImport.update({
  id: '/forge',
  path: '/forge',
  getParentRoute: () => ApiAgentRoute,
} as any)
const ApiAgentKeyRoute = ApiAgentKeyRouteImport.update({
  id: '/key',
  path: '/key',
  getParentRoute: () => ApiAgentRoute,
} as any)
const ApiAgentOpenapiRoute = ApiAgentOpenapiRouteImport.update({
  id: '/openapi',
  path: '/openapi',
  getParentRoute: () => ApiAgentRoute,
} as any)
const ApiAgentPresenceRoute = ApiAgentPresenceRouteImport.update({
  id: '/presence',
  path: '/presence',
  getParentRoute: () => ApiAgentRoute,
} as any)
const ApiAgentSkillRoute = ApiAgentSkillRouteImport.update({
  id: '/skill',
  path: '/skill',
  getParentRoute: () => ApiAgentRoute,
} as any)
const ApiAgentVerifyRoute = ApiAgentVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => ApiAgentRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/agentes': typeof AgentesRoute
  '/chat': typeof ChatRoute
  '/evidence': typeof EvidenceRouteWithChildren
  '/findings': typeof FindingsRouteWithChildren
  '/goals': typeof GoalsRouteWithChildren
  '/login': typeof LoginRoute
  '/memory': typeof MemoryRoute
  '/settings': typeof SettingsRoute
  '/uso': typeof UsoRoute
  '/verificar': typeof VerificarRoute
  '/api/agent': typeof ApiAgentRouteWithChildren
  '/evidence/$evidenceId': typeof EvidenceEvidenceIdRoute
  '/findings/$findingId': typeof FindingsFindingIdRoute
  '/goals/$goalId': typeof GoalsGoalIdRoute
  '/evidence/': typeof EvidenceIndexRoute
  '/findings/': typeof FindingsIndexRoute
  '/goals/': typeof GoalsIndexRoute
  '/api/agent/forge': typeof ApiAgentForgeRoute
  '/api/agent/key': typeof ApiAgentKeyRoute
  '/api/agent/openapi': typeof ApiAgentOpenapiRoute
  '/api/agent/presence': typeof ApiAgentPresenceRoute
  '/api/agent/skill': typeof ApiAgentSkillRoute
  '/api/agent/verify': typeof ApiAgentVerifyRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/agentes': typeof AgentesRoute
  '/chat': typeof ChatRoute
  '/login': typeof LoginRoute
  '/memory': typeof MemoryRoute
  '/settings': typeof SettingsRoute
  '/uso': typeof UsoRoute
  '/verificar': typeof VerificarRoute
  '/api/agent': typeof ApiAgentRouteWithChildren
  '/evidence/$evidenceId': typeof EvidenceEvidenceIdRoute
  '/findings/$findingId': typeof FindingsFindingIdRoute
  '/goals/$goalId': typeof GoalsGoalIdRoute
  '/evidence': typeof EvidenceIndexRoute
  '/findings': typeof FindingsIndexRoute
  '/goals': typeof GoalsIndexRoute
  '/api/agent/forge': typeof ApiAgentForgeRoute
  '/api/agent/key': typeof ApiAgentKeyRoute
  '/api/agent/openapi': typeof ApiAgentOpenapiRoute
  '/api/agent/presence': typeof ApiAgentPresenceRoute
  '/api/agent/skill': typeof ApiAgentSkillRoute
  '/api/agent/verify': typeof ApiAgentVerifyRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/agentes': typeof AgentesRoute
  '/chat': typeof ChatRoute
  '/evidence': typeof EvidenceRouteWithChildren
  '/findings': typeof FindingsRouteWithChildren
  '/goals': typeof GoalsRouteWithChildren
  '/login': typeof LoginRoute
  '/memory': typeof MemoryRoute
  '/settings': typeof SettingsRoute
  '/uso': typeof UsoRoute
  '/verificar': typeof VerificarRoute
  '/api/agent': typeof ApiAgentRouteWithChildren
  '/evidence/$evidenceId': typeof EvidenceEvidenceIdRoute
  '/findings/$findingId': typeof FindingsFindingIdRoute
  '/goals/$goalId': typeof GoalsGoalIdRoute
  '/evidence/': typeof EvidenceIndexRoute
  '/findings/': typeof FindingsIndexRoute
  '/goals/': typeof GoalsIndexRoute
  '/api/agent/forge': typeof ApiAgentForgeRoute
  '/api/agent/key': typeof ApiAgentKeyRoute
  '/api/agent/openapi': typeof ApiAgentOpenapiRoute
  '/api/agent/presence': typeof ApiAgentPresenceRoute
  '/api/agent/skill': typeof ApiAgentSkillRoute
  '/api/agent/verify': typeof ApiAgentVerifyRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/agentes'
    | '/chat'
    | '/evidence'
    | '/findings'
    | '/goals'
    | '/login'
    | '/memory'
    | '/settings'
    | '/uso'
    | '/verificar'
    | '/api/agent'
    | '/evidence/$evidenceId'
    | '/findings/$findingId'
    | '/goals/$goalId'
    | '/evidence/'
    | '/findings/'
    | '/goals/'
    | '/api/agent/forge'
    | '/api/agent/key'
    | '/api/agent/openapi'
    | '/api/agent/presence'
    | '/api/agent/skill'
    | '/api/agent/verify'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/agentes'
    | '/chat'
    | '/login'
    | '/memory'
    | '/settings'
    | '/uso'
    | '/verificar'
    | '/api/agent'
    | '/evidence/$evidenceId'
    | '/findings/$findingId'
    | '/goals/$goalId'
    | '/evidence'
    | '/findings'
    | '/goals'
    | '/api/agent/forge'
    | '/api/agent/key'
    | '/api/agent/openapi'
    | '/api/agent/presence'
    | '/api/agent/skill'
    | '/api/agent/verify'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/agentes'
    | '/chat'
    | '/evidence'
    | '/findings'
    | '/goals'
    | '/login'
    | '/memory'
    | '/settings'
    | '/uso'
    | '/verificar'
    | '/api/agent'
    | '/evidence/$evidenceId'
    | '/findings/$findingId'
    | '/goals/$goalId'
    | '/evidence/'
    | '/findings/'
    | '/goals/'
    | '/api/agent/forge'
    | '/api/agent/key'
    | '/api/agent/openapi'
    | '/api/agent/presence'
    | '/api/agent/skill'
    | '/api/agent/verify'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AgentesRoute: typeof AgentesRoute
  ChatRoute: typeof ChatRoute
  EvidenceRoute: typeof EvidenceRouteWithChildren
  FindingsRoute: typeof FindingsRouteWithChildren
  GoalsRoute: typeof GoalsRouteWithChildren
  LoginRoute: typeof LoginRoute
  MemoryRoute: typeof MemoryRoute
  SettingsRoute: typeof SettingsRoute
  UsoRoute: typeof UsoRoute
  VerificarRoute: typeof VerificarRoute
  ApiAgentRoute: typeof ApiAgentRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agentes': {
      id: '/agentes'
      path: '/agentes'
      fullPath: '/agentes'
      preLoaderRoute: typeof AgentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/findings': {
      id: '/findings'
      path: '/findings'
      fullPath: '/findings'
      preLoaderRoute: typeof FindingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uso': {
      id: '/uso'
      path: '/uso'
      fullPath: '/uso'
      preLoaderRoute: typeof UsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verificar': {
      id: '/verificar'
      path: '/verificar'
      fullPath: '/verificar'
      preLoaderRoute: typeof VerificarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent': {
      id: '/api/agent'
      path: '/api/agent'
      fullPath: '/api/agent'
      preLoaderRoute: typeof ApiAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence/': {
      id: '/evidence/'
      path: '/'
      fullPath: '/evidence/'
      preLoaderRoute: typeof EvidenceIndexRouteImport
      parentRoute: typeof EvidenceRoute
    }
    '/evidence/$evidenceId': {
      id: '/evidence/$evidenceId'
      path: '/$evidenceId'
      fullPath: '/evidence/$evidenceId'
      preLoaderRoute: typeof EvidenceEvidenceIdRouteImport
      parentRoute: typeof EvidenceRoute
    }
    '/findings/': {
      id: '/findings/'
      path: '/'
      fullPath: '/findings/'
      preLoaderRoute: typeof FindingsIndexRouteImport
      parentRoute: typeof FindingsRoute
    }
    '/findings/$findingId': {
      id: '/findings/$findingId'
      path: '/$findingId'
      fullPath: '/findings/$findingId'
      preLoaderRoute: typeof FindingsFindingIdRouteImport
      parentRoute: typeof FindingsRoute
    }
    '/goals/': {
      id: '/goals/'
      path: '/'
      fullPath: '/goals/'
      preLoaderRoute: typeof GoalsIndexRouteImport
      parentRoute: typeof GoalsRoute
    }
    '/goals/$goalId': {
      id: '/goals/$goalId'
      path: '/$goalId'
      fullPath: '/goals/$goalId'
      preLoaderRoute: typeof GoalsGoalIdRouteImport
      parentRoute: typeof GoalsRoute
    }
    '/api/agent/forge': {
      id: '/api/agent/forge'
      path: '/forge'
      fullPath: '/api/agent/forge'
      preLoaderRoute: typeof ApiAgentForgeRouteImport
      parentRoute: typeof ApiAgentRoute
    }
    '/api/agent/key': {
      id: '/api/agent/key'
      path: '/key'
      fullPath: '/api/agent/key'
      preLoaderRoute: typeof ApiAgentKeyRouteImport
      parentRoute: typeof ApiAgentRoute
    }
    '/api/agent/openapi': {
      id: '/api/agent/openapi'
      path: '/openapi'
      fullPath: '/api/agent/openapi'
      preLoaderRoute: typeof ApiAgentOpenapiRouteImport
      parentRoute: typeof ApiAgentRoute
    }
    '/api/agent/presence': {
      id: '/api/agent/presence'
      path: '/presence'
      fullPath: '/api/agent/presence'
      preLoaderRoute: typeof ApiAgentPresenceRouteImport
      parentRoute: typeof ApiAgentRoute
    }
    '/api/agent/skill': {
      id: '/api/agent/skill'
      path: '/skill'
      fullPath: '/api/agent/skill'
      preLoaderRoute: typeof ApiAgentSkillRouteImport
      parentRoute: typeof ApiAgentRoute
    }
    '/api/agent/verify': {
      id: '/api/agent/verify'
      path: '/verify'
      fullPath: '/api/agent/verify'
      preLoaderRoute: typeof ApiAgentVerifyRouteImport
      parentRoute: typeof ApiAgentRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EvidenceRouteChildren {
  EvidenceEvidenceIdRoute: typeof EvidenceEvidenceIdRoute
  EvidenceIndexRoute: typeof EvidenceIndexRoute
}

const EvidenceRouteChildren: EvidenceRouteChildren = {
  EvidenceEvidenceIdRoute: EvidenceEvidenceIdRoute,
  EvidenceIndexRoute: EvidenceIndexRoute,
}

const EvidenceRouteWithChildren = EvidenceRoute._addFileChildren(
  EvidenceRouteChildren,
)

interface FindingsRouteChildren {
  FindingsFindingIdRoute: typeof FindingsFindingIdRoute
  FindingsIndexRoute: typeof FindingsIndexRoute
}

const FindingsRouteChildren: FindingsRouteChildren = {
  FindingsFindingIdRoute: FindingsFindingIdRoute,
  FindingsIndexRoute: FindingsIndexRoute,
}

const FindingsRouteWithChildren = FindingsRoute._addFileChildren(
  FindingsRouteChildren,
)

interface GoalsRouteChildren {
  GoalsGoalIdRoute: typeof GoalsGoalIdRoute
  GoalsIndexRoute: typeof GoalsIndexRoute
}

const GoalsRouteChildren: GoalsRouteChildren = {
  GoalsGoalIdRoute: GoalsGoalIdRoute,
  GoalsIndexRoute: GoalsIndexRoute,
}

const GoalsRouteWithChildren = GoalsRoute._addFileChildren(GoalsRouteChildren)

interface ApiAgentRouteChildren {
  ApiAgentForgeRoute: typeof ApiAgentForgeRoute
  ApiAgentKeyRoute: typeof ApiAgentKeyRoute
  ApiAgentOpenapiRoute: typeof ApiAgentOpenapiRoute
  ApiAgentPresenceRoute: typeof ApiAgentPresenceRoute
  ApiAgentSkillRoute: typeof ApiAgentSkillRoute
  ApiAgentVerifyRoute: typeof ApiAgentVerifyRoute
}

const ApiAgentRouteChildren: ApiAgentRouteChildren = {
  ApiAgentForgeRoute: ApiAgentForgeRoute,
  ApiAgentKeyRoute: ApiAgentKeyRoute,
  ApiAgentOpenapiRoute: ApiAgentOpenapiRoute,
  ApiAgentPresenceRoute: ApiAgentPresenceRoute,
  ApiAgentSkillRoute: ApiAgentSkillRoute,
  ApiAgentVerifyRoute: ApiAgentVerifyRoute,
}

const ApiAgentRouteWithChildren = ApiAgentRoute._addFileChildren(
  ApiAgentRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AgentesRoute: AgentesRoute,
  ChatRoute: ChatRoute,
  EvidenceRoute: EvidenceRouteWithChildren,
  FindingsRoute: FindingsRouteWithChildren,
  GoalsRoute: GoalsRouteWithChildren,
  LoginRoute: LoginRoute,
  MemoryRoute: MemoryRoute,
  SettingsRoute: SettingsRoute,
  UsoRoute: UsoRoute,
  VerificarRoute: VerificarRoute,
  ApiAgentRoute: ApiAgentRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
