import type { Case, Evidence, Report } from '@internet-brain-os/shared';

export interface ObsidianNote {
  readonly path: string;
  readonly content: string;
}

export interface ObsidianExportBundle {
  readonly notes: readonly ObsidianNote[];
}

/** Converts kernel objects into deterministic Markdown notes suitable for an Obsidian vault. */
export class ObsidianExporter {
  exportCase(caseRecord: Case, evidence: readonly Evidence[] = [], report?: Report): ObsidianExportBundle {
    const notes: ObsidianNote[] = [
      {
        path: `Cases/${safeFileName(caseRecord.title)}.md`,
        content: renderCase(caseRecord, evidence),
      },
    ];

    for (const item of evidence) {
      notes.push({
        path: `Evidence/${safeFileName(item.id)}.md`,
        content: renderEvidence(item),
      });
    }

    if (report) {
      notes.push({
        path: `Reports/${safeFileName(report.title)}.md`,
        content: renderReport(report),
      });
    }

    return { notes };
  }
}

function renderCase(caseRecord: Case, evidence: readonly Evidence[]): string {
  return [
    `# ${caseRecord.title}`,
    '',
    '## Objective',
    caseRecord.objective,
    '',
    `**Status:** ${caseRecord.status}`,
    `**Created:** ${caseRecord.createdAt}`,
    `**Updated:** ${caseRecord.updatedAt}`,
    caseRecord.tags.length ? `**Tags:** ${caseRecord.tags.join(', ')}` : '',
    '',
    '## Evidence',
    ...evidence.map((item) => `- [[${item.id}]]${item.sourceUrl ? ` — ${item.sourceUrl}` : ''}`),
    '',
  ].filter(Boolean).join('\n');
}

function renderEvidence(evidence: Evidence): string {
  return [
    `# Evidence ${evidence.id}`,
    '',
    `- **Type:** ${evidence.contentType}`,
    `- **Captured:** ${evidence.capturedAt}`,
    `- **Confidence:** ${evidence.confidence}`,
    evidence.sourceUrl ? `- **Source:** ${evidence.sourceUrl}` : '',
    evidence.extractionMethod ? `- **Extraction:** ${evidence.extractionMethod}` : '',
    '',
    '## Summary',
    evidence.summary ?? 'No summary available.',
    '',
    '## Raw Content',
    evidence.rawText ?? 'No raw content available.',
    '',
  ].filter(Boolean).join('\n');
}

function renderReport(report: Report): string {
  return [
    `# ${report.title}`,
    '',
    `**Generated:** ${report.generatedAt}`,
    `**Generated by:** ${report.generatedBy}`,
    `**Confidence:** ${report.confidence}`,
    '',
    ...report.sections.flatMap((section) => [
      `## ${section.heading}`,
      section.content,
      section.evidenceIds.length ? `\nEvidence: ${section.evidenceIds.map((id) => `[[${id}]]`).join(', ')}` : '',
      '',
    ]),
    '## Limitations',
    ...report.limitations.map((limitation) => `- ${limitation}`),
    '',
  ].filter(Boolean).join('\n');
}

function safeFileName(value: string): string {
  return value.trim().replace(/[\\/:*?"<>|]/g, '-').replace(/\s+/g, ' ').slice(0, 160) || 'Untitled';
}
